# This file was generated by GoReleaser. DO NOT EDIT.
cask "streams" do
  name "streams"
  desc "AI-powered software development pipeline orchestrator"
  homepage "https://github.com/z-morgan/streams"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "streams"

  on_macos do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_amd64.tar.gz"
      sha256 "8c37ec234649502e5d851eac64186d86f507273a488d8aa34386cecf2e43efca"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_arm64.tar.gz"
      sha256 "30f4accac0313a6109f6349e5ed37cff96273aa5b63dac4b9bb74f0189201258"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_amd64.tar.gz"
      sha256 "19daa53f5cc592d410cfe89b379eaf54e8eb59c3f3d645cd3b4d2a6f1098958c"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_arm64.tar.gz"
      sha256 "e65d1f6d35acebe0fba590e6b3cc80abb0028c56cd372b3c5e9c17e57aa15997"
    end
  end

  # No zap stanza required
end
