# This file was generated by GoReleaser. DO NOT EDIT.
cask "streams" do
  name "streams"
  desc "AI-powered software development pipeline orchestrator"
  homepage "https://github.com/z-morgan/streams"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "streams"

  on_macos do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_amd64.tar.gz"
      sha256 "eba38ad684253d9067f91a00ac60cc6d4392c24fcbb839600ec6fd12ea8dc3b3"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_arm64.tar.gz"
      sha256 "38dab99f00cd65bcf2c2449dcaea556a36c083e7027299b659eadffffce9c8e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_amd64.tar.gz"
      sha256 "d87f4b95b5b2d01c433a4724eb8b55f77eeacf54765bdbdf68698aad56938be3"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_arm64.tar.gz"
      sha256 "33511da83315b190ee8bddf168814324c90007e6983c1b73c9703e6cbc6203ef"
    end
  end

  # No zap stanza required
end
