# This file was generated by GoReleaser. DO NOT EDIT.
cask "streams" do
  name "streams"
  desc "AI-powered software development pipeline orchestrator"
  homepage "https://github.com/z-morgan/streams"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "streams"

  on_macos do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_amd64.tar.gz"
      sha256 "521524fd3157007a72d2bf842d9da1328fae0823d3d99b1fc0fc3c2060617284"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_darwin_arm64.tar.gz"
      sha256 "e5e245fc0e1a70b0d17802e2351a3464690047104e02a9081aba4aca475535a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_amd64.tar.gz"
      sha256 "ada3fc5245af84981071410bc1fdbd187e7fea1aee5063da2dfd0f65996356bf"
    end
    on_arm do
      url "https://github.com/z-morgan/streams/releases/download/v#{version}/streams_#{version}_linux_arm64.tar.gz"
      sha256 "870ff262710f3a0ce1c03059c8914dd9a68020e2b1c4807db57ccf6dfb4b69df"
    end
  end

  # No zap stanza required
end
