# This file was generated by GoReleaser. DO NOT EDIT.
cask "umpire" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "b70bff37072fefbb5857193765d67e5eaaa0e93546a31e5fb062edb96991974e"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "47761b80b3b36563b930b9f0dff61d70dc051abe218a3fbd3075b9f3b38ddccd"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "844c7922c663f069f25bb4a114cb6b4d8a1528bfda05332984028637178204bf"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "895a7d3742637f3861e3c06ecd2e9e36e9c55b0c23bca43e51439fc3ef1cfa57"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_amd64.tar.gz"
    end
  end

  name "umpire"
  desc "Local code review tool with a GitHub-like UI"
  homepage "https://github.com/z-morgan/umpire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umpire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umpire"]
    end
  end

  # No zap stanza required
end
