# This file was generated by GoReleaser. DO NOT EDIT.
cask "umpire" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "13bd1fddc2810d280dced148947627e1d9d85e3bf9a71dcd84530d7b43e9621b"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcee3df85c9d0e1b86167eb9e4b86c1c96bfac3967c926f43882cb0d6a580531"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29cd5e0c571b620edd5bc5c5bdb020e68a87c3ef17e0e7d049f5bea05d1ccbbc"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "494616ea788024b6b9b655aac74446b32827a801a08e5ab4e2cf014dce2e6fc9"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_arm64.tar.gz"
    end
  end

  name "umpire"
  desc "Local code review tool with a GitHub-like UI"
  homepage "https://github.com/z-morgan/umpire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umpire"

  # No zap stanza required

end
