# This file was generated by GoReleaser. DO NOT EDIT.
cask "umpire" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "1123eb29ec88b1ad61d7b217f778b39504384c8fe00f87c965914b63b9b6751f"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1518eae840d29fc12e2f71be6daadc2a7fa023ae9e987f383dd4544c6917178"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6482415350a6ad09d6c7c3e752869e7226b9dbd8d93b840414148d6122b8a891"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb32c19fafd466381e66c717aa373be6dced0c3e03fc9935ea354ba5228f104f"
      url "https://github.com/z-morgan/umpire/releases/download/v#{version}/umpire_#{version}_linux_arm64.tar.gz"
    end
  end

  name "umpire"
  desc "Local code review tool with a GitHub-like UI"
  homepage "https://github.com/z-morgan/umpire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umpire"

  # No zap stanza required

end
